### ISSUE TITLE
Add and Edit description

### ISSUE THREAD

**Issue by max200809** [rcemper/SSH-for-IRIS-container#3]
Add variable to dockerfile
ENV TZ= UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

Build hangs on region selection
Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.
1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
2. America     5. Arctic     8. Europe    11. SystemV
3. Antarctica  6. Asia       9. Indian    12. US
Geographic area:

**Comment by rcemper** [comment]
no issue with WSL2
